#!/bin/bash
cd ~/
rm -rf .bashrc
rm -rf /data/data/com.termux/files/usr/Term-lock/password.txt
rm -rf /data/data/com.termux/files/usr/Term-lock/motd
cd ~/
echo "

Welcome to Termux!

Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on libera.chat

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

" >> motd

mv motd /data/data/com.termux/files/usr/etc/
clear
echo "Locked remove  successfully"

